---
- name: Deploy Nextcloud and Monitoring Stack
  hosts: homelab
  become: yes  # This tells Ansible to use 'sudo' for these tasks
  tasks:
    - name: Ensure the deployment directory exists on the server
      file:
        path: /home/hodhod/cloud-stack
        state: directory
        owner: hodhod
        group: hodhod

    - name: Copy docker-compose and config files to the server
      copy:
        src: "{{ item }}"
        dest: /home/hodhod/cloud-stack/
        owner: hodhod
        group: hodhod
      loop:
        - files/docker-compose.yml
        - files/prometheus.yml
        - files/.env

    - name: Start the Docker Compose stack
      command: docker compose up -d
      args:
        chdir: /home/hodhod/cloud-stack
